# Generated by Django 3.2.4 on 2021-08-06 02:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_offer_sent', models.DateTimeField(auto_now_add=True)),
                ('date_offer_received', models.DateTimeField(blank=True, null=True)),
                ('date_offer_replied', models.DateTimeField(blank=True, null=True)),
                ('is_received', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(blank=True, default=False, null=True)),
                ('is_counteroffer', models.BooleanField(blank=True, default=False, null=True)),
                ('offer_item_receive', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_offered_receiver', to='trans.listing')),
                ('offer_item_send1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_offered_sender1', to='trans.listing')),
                ('offer_item_send2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_offered_sender2', to='trans.listing')),
                ('offer_item_send3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='item_offered_sender3', to='trans.listing')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='received_offers', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sent_offers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
