# Generated by Django 3.2.4 on 2021-06-28 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='Default City', max_length=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.CharField(default='USA', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='is_billing',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='address',
            name='is_inactive',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='address',
            name='is_shipping',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='address',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.person'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='postalcode',
            field=models.CharField(default=12345, max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(default='CA', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='street1',
            field=models.CharField(default='123 Street', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='street2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tradecredits',
            name='credit',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradecredits',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trade_credits', to='accounts.user'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='person', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
