# Generated by Django 3.2.4 on 2021-06-28 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_tradecredits_credit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradecredits',
            options={'verbose_name': 'Trade Credits', 'verbose_name_plural': 'Trade Credits'},
        ),
        migrations.AddField(
            model_name='person',
            name='is_cellphone',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
