# Generated by Django 3.2.5 on 2021-08-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20210817_1350'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='forgot_password_token',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
    ]
