# Generated by Django 3.2.4 on 2021-06-24 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('type', models.BooleanField(blank=True, default=0, null=True)),
                ('source', models.CharField(max_length=120, null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('release_notes', models.CharField(blank=True, max_length=255, null=True)),
                ('edition_type', models.CharField(blank=True, max_length=30, null=True)),
                ('edition_size', models.IntegerField(blank=True, null=True)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_retired', models.BooleanField(blank=True, null=True, verbose_name='retired')),
                ('retired_date', models.DateField(blank=True, null=True)),
                ('has_ap', models.BooleanField(blank=True, default=False, null=True, verbose_name='artist proof')),
                ('ap_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('has_pp', models.BooleanField(blank=True, default=False, null=True, verbose_name='pre-production')),
                ('pp_qty', models.IntegerField(blank=True, default=0, null=True)),
                ('descrip', models.TextField(blank=True, null=True, verbose_name='description')),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('date_item_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pinventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_public_all', models.BooleanField(default=True, verbose_name='public')),
                ('is_public_listed', models.BooleanField(default=True, verbose_name='only listed items')),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pinventory', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'pinventories',
            },
        ),
        migrations.CreateModel(
            name='Pin',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.item')),
                ('is_included_in_set', models.BooleanField(default=False, verbose_name='part of a set')),
                ('is_fantasy', models.BooleanField(default=False, verbose_name='fantasy')),
            ],
            bases=('main.item',),
        ),
        migrations.CreateModel(
            name='PinSet',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.item')),
                ('qty_in_set', models.IntegerField(verbose_name='quantity of pins in set')),
            ],
            bases=('main.item',),
        ),
        migrations.CreateModel(
            name='UserEstimatedValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('est_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='estimated value')),
                ('value_date', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PinventoryContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('date_item_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('date_qty_update', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date updated')),
                ('date_removed', models.DateTimeField(blank=True, null=True)),
                ('hidden_for_set', models.BooleanField(default=0)),
                ('status', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinventorycontent', to='main.item')),
                ('pinventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinventorycontent', to='main.pinventory')),
            ],
        ),
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to=None)),
                ('is_primary', models.BooleanField(default=True)),
                ('date_image_added', models.DateTimeField(auto_now_add=True, verbose_name='date added')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.item')),
            ],
        ),
        migrations.CreateModel(
            name='PinSetContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pin_in_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pin')),
                ('set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.pinset')),
            ],
        ),
    ]
