# Generated by Django 3.2.4 on 2021-07-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
