# Generated by Django 3.2.4 on 2021-08-23 20:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trans', '0002_tradeoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('is_received', models.BooleanField(default=False)),
                ('date_received', models.DateTimeField(blank=True, null=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='tradeoffer',
            name='date_offer_received',
        ),
        migrations.RemoveField(
            model_name='tradeoffer',
            name='date_offer_sent',
        ),
        migrations.RemoveField(
            model_name='tradeoffer',
            name='id',
        ),
        migrations.RemoveField(
            model_name='tradeoffer',
            name='is_received',
        ),
        migrations.RemoveField(
            model_name='tradeoffer',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='tradeoffer',
            name='sender',
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('messagetype_ptr', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trans.messagetype')),
                ('message_text', models.TextField()),
            ],
            bases=('trans.messagetype',),
        ),
        migrations.AddField(
            model_name='tradeoffer',
            name='messagetype_ptr',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='trans.messagetype'),
            preserve_default=False,
        ),
    ]
