# Generated by Django 3.2.4 on 2021-07-01 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210630_1927'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='payment_option',
            new_name='gateway',
        ),
        migrations.RemoveField(
            model_name='order',
            name='order_key',
        ),
    ]
