# Generated by Django 3.2.5 on 2021-07-21 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trans', '0001_initial'),
        ('orders', '0010_auto_20210721_0901'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date_created']},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='created_date',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='updated',
            new_name='last_update',
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='trans.listing'),
        ),
    ]
