# Generated by Django 3.2.4 on 2021-08-23 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_itemimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='needs_new_pic',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
